defaults:
  - env: hmm
  - model: hmm
  - train: default
  - loss: default
  - policy: random
  - eval: default
  - operator: default
  - vq: default
  - preset: default
  - _self_

seed: 123
device: auto

hydra:
  run:
    dir: .
  sweep:
    dir: .
