type: mechanism
elasticity_env0: 0.9
elasticity_env1: 0.2
dt: 0.1
prediction: mse
train_env_ids: [0, 2]
test_env_ids: [1, 3]
all_env_ids: [0, 1, 2, 3]
interventions:
  - {set_vel: {obj: 0, value: 0.8}, duration: 1}
