type: object
num_objects: 3
obs_mode: structured
image_size: 32
spurious_noise: 0.1
dt: 0.1
spurious_flip_on_odd: true
prediction: label_ce
train_env_ids: [0, 2]
test_env_ids: [1, 3]
all_env_ids: [0, 1, 2, 3]
interventions:
  - {set_pos: {obj: 0, value: [0.5, 0.5]}, duration: 1}
  - {set_background: 1.0, duration: 1}
